### ISSUE TITLE
Releases do not document what OS the release was for

### ISSUE THREAD

**Issue by endobson** [kythe/kythe#165]
I'm looking to get kythe to run on my macOS machine, but it looks like the releases are not compatible with that and I need to build from source. It would be helpful if the release specified which OS it was built for.

**Comment by jrtom** [comment]
It would be helpful to get an idea of what specifically you're trying to do, and what problem you're encountering when doing it.  This issue is not actionable as is.

Generally speaking (IIRC), we're releasing source code, not binary artifacts, so I'm not sure what you mean by "which OS it was built for".  If what you meant is "what OS we use when building", we're generally building things on Linux, although @salguarnieri may be able to speak to MacOS-related builds to some extent.

**Comment by endobson** [comment]
I'm trying to test out kythe, get it to run on my machine and see what I can do with the produced data.

There is a release section on github, https://github.com/google/kythe/releases. These have tar files with built binaries in them.
E.g. https://github.com/google/kythe/releases/download/v0.0.27/kythe-v0.0.27.tar.gz

This is a built binary and doesn't describe which os it is for. The issue is that it is not documented and so the only way I can figure out what you are actually providing is by downloading it and trying it out.

**Comment by jrtom** [comment]
@endobson Sorry, I hadn't looked at our release artifacts recently and had forgotten we were also providing binaries.  Agreed that we should label our binary release artifacts by platform.
