### ISSUE TITLE
Support Code Completion in LSP Server

### ISSUE THREAD

**Issue by vitiral** [kythe/kythe#2945]
Is supporting code completion on the roadmap for Kythe's implementation of the Language Server Protocol? Code completion is a pretty important feature to bring parity to a "complete" IDE environment.

Thanks!

**Comment by creachadair** [comment]
Hi, Rett,

We don't have any current plans to add code-completion to Kythe. Code
completion requires a fairly tight integration with the UI, and Kythe isn't
really intended to be (or to replace) a UI-oriented tool like an editor or
an IDEs. Services like cross-references are meant to work in support of
such tools.

That said, I believe local code-completion tools could be augmented with
Kythe data—though so far no one's done this. The tricky part generally will
be matching up results from a pre-computed index with dynamic local results
by location. It's pretty tool-specific, though, and we haven't found a
usefully generic API for that kind of close integration.

–M

**Comment by vitiral** [comment]
Hey M,

I'm not sure I understand. You say that Kythe isnt intended to replace
those tools, which makes sense. However I'm talking about the LSP Server
which (I assume) is built on top of kythe and simply uses it's data. The
LSP isn't intended to replace an editor either, but it is intended to
support a certain API which would include code completion.

The way I would imagine implementing the code completion API is to do a
fuzzy search of the kythe index/db using context of where the user is
typing (like if they are currently typing a path "foo.bar.b") and possibly
using some type hinting. Very little would be language specific and it
would mostly rely on the kythe index/db.

Again, I'm just imagining and don't really know.

Thanks,
Rett

- sent from my Android

>

**Comment by creachadair** [comment]
Since Kythe analysis is static, it requires code that builds. Completion, by design, is intended for code that is in-progress, and generally doesn't (yet) compile or run. One could certainly use data from a Kythe index to augment local completion results, but the Kythe data won't solve the local problem of generating symbols for completion. It's an interesting and useful problem, but not one that's on our radar at the moment.

If someone wanted to integrate Kythe support atop an existing code-completion tool, that is more likely to succeed than trying to build one afresh starting from the semantic graph.

**Comment by vitiral** [comment]
Gotcha! I misread a requirement of the indexer that it should continue in
the face of errors to mean that such a case (indexing code which doesn't
compile) could be supported.

Please feel free to close.

**Comment by vitiral** [comment]
There is another point which I didn't think about, which is that I think it's a pretty rare use-case that someone would work for more than a few minutes on code that doesn't compile. The only time I can think is during refactoring. If the results of LSP services are "stale" for these times I think that is okay. For example, returning results that were valid that the last time code compiled would probably not be all that surprising to most users.

Just a possible reason not to close and why this might be feasible.

**Comment by x1ddos** [comment]
> Since Kythe analysis is static, it requires code that builds. Completion, by design, is intended for code that is in-progress, and generally doesn't (yet) compile or run

You could say the same thing about "go to definition" or "show references" features for "code that is in-progress". I don't see why completion would be any different.

**Comment by robinp** [comment]
Fundamentally it could be done. But code completion would only be available for things up to the point of indexing, which might be surprising for the users. Or say if you change the signature, you would still get code completion for the old one (or none, depending on implementation).

An other hardship is if you want context-sensitive completion (say completing on `this.foob|`, expecting to resolve to `this.foobar(...)`, not just a global function), you need the type of `this`. That in itself needs some language-specific support outside of Kythe, at which point it is questionable if Kythe is needed at all.

If you can come up with an implementation that effectively resolves types of things, but can't do proper autocomplete, then it would be a good time to revisit this issue and think further. (My subjective opinion, not representative of Kythe).

**Comment by creachadair** [comment]
> You could say the same thing about "go to definition" or "show references" features for "code that is in-progress". I don't see why completion would be any different.

That is true. An important difference, however, is that code completion is almost _exclusively_ useful during development, while jump-to-definition and cross-references are also useful for exploration, visualization, and understanding the dependencies of code even when it's not being actively developed. In fact, in many ways it is _more_ valuable then, since those activities often are being done by someone attempting to understand the code who didn't write it (and thus lacks context).

My point, however, wasn't meant to be that it's technically impossible, but that this is why Kythe doesn't include completion: Kythe is designed to work on code that builds, and incomplete code by definition doesn't build. As I said, "one could certainly use data from a Kythe index to augment local completion results, but the Kythe data won't solve the local problem of generating symbols for completion." In other words, it could be part of a solution, but does not address the issue of how to extract type information from locally-modified code.

Indeed, I think the lack of an accurate large-scale index of dependencies is one of the things that really hinders the quality of existing code-completion tools, which by nature tend to be limited to only the code the developer has actively imported into their IDE's workspace.

**Comment by robinp** [comment]
@creachadair 

> Indeed, I think the lack of an accurate large-scale index of dependencies is one of the things that really hinders the quality of existing code-completion tools, which by nature tend to be limited to only the code the developer has actively imported into their IDE's workspace.

That's an interesting point, and suggest where Kythe-based code completion could have value. Because existing, imported code can naturally be completed by existing tools. But non-imported code can't. But if it is non-imported code, local context is less likely to play a role in resolving it (it is likely a static method, otherwise the related class would have already been imported).

So a large scale Kythe backing index could help in discovering existing but non-imported functions. This can happen mainly via two approaches:

- Import-by-name, where the user starts typing something, which is resolved to a Kythe-indexed function using the (unqualified name).

- Import-by-type, where we want to get from input arg types to result type. This is similar to Haskell's `hoogle` databases (though in Haskell it arguably works better than has a chance in more imperative languages, due to purity forcing much context into the type signature, making it explicit what is an in/out parameter, etc).

Both approaches would need some post-processing of the Kythe database, as it currently doesn't index by (unqualified) name or types either.

**Comment by vladdu** [comment]
Since the ticket is not close, I hope it's ok to add some thoughts.

What I would find useful to use a pregenerated index for is for third party libraries. These are read only in the current project, and one needs to do code completion on them. So if one could detect and load the pregenerated index, one would not need to parse the library's source code.

Whether this is something for Kythe or for tools building on it, that is another discussion.

**Comment by vitiral** [comment]
Sorry for commenting way later, but I had a few more thoughts

> An other hardship is if you want context-sensitive completion (say completing on `this.foob|`, expecting to resolve to `this.foobar(...)`, not just a global function), you need the type of `this`. That in itself needs some language-specific support outside of Kythe

I find this objection surprising. How does Kythe support goto definition if it doesn't know the type of `this`?

Personally I feel that the trade-offs are all well-worth it. A theoretical completer could prioritize local file/scope for non-compiling code, and use kythe for everything else -- possibly filtering imported items to be higher priority, which I assume is information it can also get from kythe. These are engineering problems that a completer can easily implement given a kythe database.

**Comment by shahms** [comment]
Kythe only indexes well-formed code, but would certainly know the type of "this" in that context.  The problem is that if you're actively editing a file (and thus expecting code completion) it is ipso facto not well-formed. In this context, Kythe generally works best in conjunction with a more traditional langserver for locally modified files.

**Comment by creachadair** [comment]
I'd like to try to clarify a couple of points here:

> I find this objection surprising. How does Kythe support goto definition if it doesn't know the type of `this`?

It's not really an objection—I don't think anyone disagrees that local completions are useful for developers. A local development environment has fundamentally different API and performance requirements from offline indexing, however, and that leads to very different technical choices. The two environments can share _data_, but there is typically not much implementation overlap.

IDEs are able to generate completions for incomplete code by providing application-specific, language-specific custom tools. That requires a "project" (or "workspace", or similar) to explicitly track the source and its dependencies, and the user is forced to curate that workspace. What the workspace tracks, and how, is all application-specific, ad hoc, non-standard, and relies on carefully chosen shortcuts to make local tools work efficiently. That's fine for people using that IDE, and as long as ~everything fits in the project.

In practice, though, most of a non-trivial project's dependency footprint lies _outside_ the boundaries of this curated environment—which leads to a tradeoff between pulling the whole graph into the IDE (which degrades performance and indexing times) and relying on some kind of "external index". Like a "sufficiently smart compiler", external indexing is mostly discussed in the abstract: The tools IDEs use to get good performance on local files don't scale out because they would require someone to define workspaces for the world.

At a high level, Kythe is designed to tackle the problem of building a large-scale offline index. It prioritizes accuracy, completeness, and faithfulness to the production tools. It's not designed to handle incomplete code, and is intended to minimally constrain the development, build, and deployment environment for the code under index. These aren't the choices one would make if the only goal were to provide quick auto-completions, and it means that you can't just drop a Kythe indexer into someone's local development environment and expect to get sub-100ms completions from half-written code. Nonetheless, the index that results turns out to be quite useful, and the data from a global index _could_ be used to reinforce local, environment-specific tools.

> Personally I feel that the trade-offs are all well-worth it. A theoretical completer could prioritize local file/scope for non-compiling code, and use kythe for everything else -- possibly filtering imported items to be higher priority, which I assume is information it can also get from kythe. These are engineering problems that a completer can easily implement given a kythe database.

I'm not sure what "trade-offs" you mean in this case—interactive code tooling and offline indexing are completely different design spaces, and the fact that they both work on source code doesn't mean they are interchangeable. That said, I think you're absolutely right that the two approaches can work together, and that a hybrid system can give programmers the benefits of both. As I said in some of the earlier comments above, I think that's the right way to address the problem.

**Comment by vitiral** [comment]
Okay, I think this has been appropriately answered. An LSP server could be implemented which _uses_ kythe, but kythe can't be used directly because it would need more information for partial code.
