### ISSUE TITLE
Looking for resources to use Kythe

### ISSUE THREAD

**Issue by PoignardAzur** [kythe/kythe#3327]
I recently stumbled upon Kythe, and I'm interested in the project, but the official documentation seems rather opaque to me.

Let's say I want to create a Kythe-powered CMake package for the Atom editor. 
* What resources should I use?
* What commands do I need to run from Node.js to create a process I can communicate with?
* How do I feed CMake build files and C++ source files to that process?
* How do I use the generated AST data to display eg error diagnostics and jump-to-file instructions?

The [existing documentation](https://kythe.io/docs/kythe-compatible-compilers.html) is rather unhelpful with these questions. The information I'm looking for is often described as "outside the scope of this document", with no information regarding which documents *do* cover the subject.

**Comment by danielmoy-google** [comment]
Hey, @shahms worked a bit on some CMake extraction, but I don't know if that's in a completely working state (yet?).

> What resources should I use?

Generally for Kythe you need 4 main bits:

* Extractor - instrumenting your builder in such a way that you can run an indexer.  This exists for C++/Bazel, but I don't know if we have C++/CMake working.
* Indexing - pulling out the interesting data from your language's LSP.  There's a C++ indexer already that you can use, though I don't know exactly how that interops with CMake.
* Postprocessing - collect data from indexing into a serveable format
* Serving - running a service to serve your data.

This is touched on briefly at the end of https://kythe.io/docs/kythe-overview.html, and there's some examples in https://github.com/kythe/kythe/blob/master/kythe/examples/bazel/kythe-index.sh

> What commands do I need to run from Node.js to create a process I can communicate with?

I have no idea what you mean by 'run from Node.js', sorry.  I have never worked from Node.js, and I lack the context to really understand what you're talking about here.

> for the Atom editor.

For editors specifically, LSP is a reasonable way to hook in to provide the UI bits.  There is code for much of that in kythe/go/languagesever.  Atom itself appears to support LSP here: https://github.com/atom/atom-languageclient

**Comment by PoignardAzur** [comment]
Thank you for your answer 👍 

> pulling out the interesting data from your language's LSP

You mean DSL?

> I have no idea what you mean by 'run from Node.js', sorry.

I mentioned Node.js because it's the runtime of the Atom editor. More generally, my question would be "how do you invoke existing Kythe building blocks from an arbitrary language/process?".

I'll look into the script you linked and into `kythe/go/languageserver`, and get back to you, but at first glance, these seem to be fairly internal uses, not intended to be transparent to outside developers.

Is there a public toolchain that can be plugged together to make a coherent developer experience? You mention the Language Server Protocol; it can be used from vs-code, atom-ide and molecule-ide; language servers are processes that receive requests on stdin and send responses on stdout. By comparison, while the serialized data structures of kythe are extensively documented, I see very little information on how to actually use the tools.

Are they executable binaries? Shared libraries? Is there a list of working Kythe extractors/indexers/post-processors sorted by builder/language/target platform?

> For editors specifically, LSP is a reasonable way to hook in to provide the UI bits.

LSP is pretty limited compared to a tool that has access to standardized parsing data. For instance, Atom has [recently released a package using tree-sitter](https://blog.atom.io/2018/10/23/atom-1-32.html), an incremental parsing library that allows eg code-folding that LSP can't really provide.

> There is code for much of that in kythe/go/languagesever

I'll check it out. Is the code in there go-specific, or is there some executable that can eg pack arbitrary extractor+indexer libs into a language server?

**Comment by danielmoy-google** [comment]
> You mean DSL?

Yea sorry I meant AST.  I was thinking ahead to the rest of the reply and had LSP on the brain already.

**Comment by danielmoy-google** [comment]
> More generally, my question would be "how do you invoke existing Kythe building blocks from an arbitrary language/process?".

Language?  You don't.  You have to build out new extractor/indexer support for each new language (or extractor for each new build system for a language).

Process?  It depends on how you're hooking in.  If it's things supporting LSP, then no.  If it's things where you built out support for Kythe RPC service and already have a running pipeline & serving stack on your side, then not much.  If it's some yet-doesn't-exist interface to kythe data, then yes.

> Is there a public toolchain that can be plugged together to make a coherent developer experience?

Not to my knowledge, no.  Kythe is one piece of a larger stack.  For example it backs the semantic cross referenes on Cloud Source Repository's code search, and Google's own internal code search.

> Are they executable binaries? Shared libraries?

The end result of Kythe itself is usually an RPC service that talks over a specific interface - see `kythe/proto/xref.proto`.  Kythe LSP can bridge the gap between that service and an IDE's LSP plugin.

> I'll check it out. Is the code in there go-specific, or is there some executable that can eg pack arbitrary extractor+indexer libs into a language server?

It's not golang specific, but it's also not about packaging extractor+indexer libs into LSP.  It's for dealing with serving format data, via an RPC service, IIRC.

**Comment by danielmoy-google** [comment]
> Is there a list of working Kythe extractors/indexers/post-processors sorted by builder/language/target platform?

I don't think we have externally visible docs on this.  Yet?

**Comment by jaysachs** [comment]
> Just to be explicit, I'm getting a strong feeling that Kythe is intended (or at least, used) more as an internal Google project than a public-facing tool for wide use by tool writers, eg people making editor plugins. 

I'm sorry you're finding it challenging to adopt Kythe. It is definitely is not intended to be Google-internal only. We're very aware of the large gaps between our vision and actuality. 

> I'm making that assumption because:
> 
> * No CMake support.

One of the hardest and most important problems to solve is how to reliably instrument a project's build. Bazel is the first, since it lends itself very naturally to instrumentation via extra_actions (and very obviously shares a great deal with internal build tools). For various reasons, we've chosen to prioritize Maven and Gradle next; one of those is that they are less open. NPM, while not truly a "build system" is also in our targets. CMake in fact is proposed next, but we have only so much bandwidth. We'd welcome contributions.

> * Few languages supported (compared to LSP or tree-sitter).

I'm not clear how you mean this. If you mean "few languages supported in the index", we are working on opening up other languages. In the past week, we've added a protobuf extractor/indexer. We are aiming to add more. If you mean something else, see my response to the next item.

> * The C++ support requires using one specific builder, and is implemented in an undocumented `example/` folder.

I believe you're asking "hey, I want to try this out on my repo", and there's no pushbutton script to generate the index. We're painfully aware of this; it is something I'd very much like to see addressed. Suggestions on what you'd want to see here would be very welcome.

> * No official lists of Kythe-based tools that can be used together on a project.

Can you flesh this out a bit? Is this similar to the immediately preceding question about "where are the simple instructions or script to quickly get this all running together end-end?" ?

> * The tools using the Kythe format seem mostly Google-related (eg a Go parser).

I don't understand this.

> which leads me to guess that most of the information I'm looking for is informally delivered from Google employee to employee. Given that the project was opened to the public 4 years ago, this is unlikely to change in the near future.
> 
> Is that a correct assessment?

I don't believe so. What we do have in Google is a large-scale implementation of it all from the various components. As you bump into it, we are missing any kind of integration setup here in the open, and we want to change that. What we have is a box full of powerful but unusual looking tools and components, but no real guidance on how to put them together usefully. I completely agree that's a gap. We have a goal to address that, but we also do not have infinite resources to devote to it. Again, I'll turn this into a request to you (and others) for guidance on what kinds of things you'd find most useful.

**Comment by creachadair** [comment]
**Disclaimer:** I no longer speak for the Kythe project on an official basis, nor for Google at all—so what follows reflects my views as a long-time contributor to Kythe.

Beyond @jaysachs's points, which I think are all correct, I have a few additional higher-level comments.

All of the pain points you described here are legitimate, and in many ways I think reflect the truth that we have not spent the time engaging with external contributors that we should. That's largely my fault: We've known this to be a problem since before we launched the project, but I did not do a good job of motivating this aspect of the project to upper management, and thus it's always been un(der)funded.

Nonetheless, the reality is that Kythe is not a "product" in the sense of a tool one can check out and run on its own. It's probably better to think of Kythe as a protocol specification and some tools for working with that spec. But this is something we have never communicated very clearly, and the confusion you're describing is common. I think that we should _try_ to make it more self-contained—but I also believe we should do a better job of explaining our work in context—not just technically, but in terms of how it fits into the bigger picture of developer tools for people _not_ affiliated with Google.

I'd like to second Jay's request for guidance about what would serve your needs best. But I'd also like this to be a call to action for the Kythe team—and more importantly the organization who funds them—to spend some time addressing aspects of the project beyond the immediate, technical needs. I am all too aware of how limited the team's bandwidth is, but it would be a great advantage to both Google and external developers, if external contributors had a better channel to learn about Kythe's status, goals, motivations, and opportunities for contribution.

**Comment by PoignardAzur** [comment]
@jaysachs

> Can you flesh this out a bit? Is this similar to the immediately preceding question about "where are the simple instructions or script to quickly get this all running together end-end?" ?

Yeah, that's one of the first questions that come to mind.

Essentially, what I'm wondering is "How am I even supposed to use this? How does it make my life better?". I understand that Kythe is a storage format first intended to be used by tools, but I have no idea where these tools are or how to use them on an existing project, let alone build new tools.

> Again, I'll turn this into a request to you (and others) for guidance on what kinds of things you'd find most useful.

Would you mind setting up a meeting, either video or using some IRC equivalent (Slack / Discord / Hangouts / whatever) to discuss this in details? I don't think I can answer your question right now, because as this discussion proves, I don't understand Kythe that well, and I think I could give you better feedback with a fast back-and-forth.

I'll try to write down a list of questions and suggestions in the meantime.

**Comment by PoignardAzur** [comment]
@creachadair 

Yeah, I know your pain.

My recently-finished last-year student project was on a LSP-based IDE, and it was really easy for the whole team to get focused on technical aspects, and lose sight of the basic "How does this thing work and what button should I even click" level that new users have to go through.

**Comment by PoignardAzur** [comment]
@danielmoy-google Any news?

**Comment by danielmoy-google** [comment]
Kythe slack is up:

https://groups.google.com/d/topic/kythe/eB98dLAs024/discussion

https://kythe-project.slack.com

**Comment by robinp** [comment]
Can we get actual invites? :)

**Comment by danielmoy-google** [comment]
I was not an admin until a few minutes ago and thus unable to invite, but now am:

https://join.slack.com/t/kythe-project/shared_invite/enQtNTQ5NjIxNDMzMjcwLTI1N2ExYTAxZThiYTliMTAyMzMxNTI2NDcyNTJkZmY0MDY4MmU5MmUwZjJiNzU2YWMxNWY4MTczNzhlNTZhNmU

**Comment by PoignardAzur** [comment]
Sorry, I missed the invite, can you create another one?

**Comment by danielmoy-google** [comment]
Sent directly to your email referenced in github, let me know if it doesn't work.
