### ISSUE TITLE
Kythe URIs use `?` for query parameter sub-delimiter, consider using `&`.

### ISSUE THREAD

**Issue by robinp** [kythe/kythe#3406]
According to [Kythe URI Spec]( https://kythe.io/docs/kythe-uri-spec.html), Kythe uses URIs like `kythe://corpus?path=foo?root=bar`, where query parameters are delimited by question marks.

This tripped up an URI parsing lib I used. First I opened https://github.com/haskell/network-uri/issues/41 against a URI parsing library, but then I realized the expectation to support this is not practical. See my expansion below.

[RFC Section 3.4](https://tools.ietf.org/html/rfc3986#section-3.4) says

> The query component is indicated by the first question  mark ("?") character and terminated by a number sign ("#") character or by the end of the URI.

Ok so far.

> The characters slash ("/") and question mark ("?") may represent data within the query component.

Sounds worrying, if `?` can be a data element, using it a separator is contradictory. But the sentence uses MAY, so Kythe spec may choose to disregard it.

Then [Section 2.2](https://tools.ietf.org/html/rfc3986#section-2.2) says

>  A subset of the reserved characters (gen-delims) is used as
   delimiters of the generic URI components described in Section 3.  A
   component's ABNF syntax rule will not use the reserved or gen-delims
   rule names directly; instead, each syntax rule lists the characters
   allowed within that component (i.e., not delimiting it), and any of
   those characters that are also in the reserved set are "reserved" for
   use as subcomponent delimiters within the component.

Which if you give a long enough hard stare, (and since both `?` and `&` are in the ABNF rule of `query`), means that actually both `&` and `?` may act as subcomponent delimiter in `query`.

So if we stick to the word of the RFC strictly, Kythe spec has the right to decide so.

But if you consider that users will use stock URI parsers likely not supporting this situation, it might be more trouble to stick to the granted right of the RFC, rather than changing it to a more standard `&` as subseparator.

**Comment by robinp** [comment]
I see. For curiosity, in what other ways would stock parsers fail? Just to
know what to expect. Thank you!

**Comment by creachadair** [comment]
> I see. For curiosity, in what other ways would stock parsers fail? Just to know what to expect. Thank you!

The problems are partly syntactic and partly semantic: The structure HTTP calls the "path" is part of the corpus label in a Kythe URI. Kythe also has a notion of "path", but it is stored as an attribute so that we can distinguish the corpus label from it. The attributes of a Kythe URI are also ordered, so that there is a canonical representation—this doesn't so much affect parsing, but does affect rendering of the URI, and once you've parsed it using a given framework, there's a strong incentive to turn it back around and write the fields back out from it. 

I think there are some differences in the rules about what has to be escaped, but I would have to page the details back in to be sure.

**Comment by robinp** [comment]
Thank you!
