### ISSUE TITLE
Variadic parameters of a function should be represented as a `tapp` of a language-specific `variadic#builtin` type constructor

### ISSUE THREAD

**Issue by schroederc** [kythe/kythe#3614]
Go example:

```
//- @F defines/binding F
//- F typed FType
//- FType.node/kind tapp
//- FType param.0 FnBuiltin
//- FType param.1 EmptyTuple
//- FType param.2 EmptyTuple
//- FType param.3 VariadicInt
//- VariadicInt.node/kind tapp
//- VariadicInt param.0 VariadicBuiltin
//- VariadicInt param.1 IntBuiltin
func F(a ...int) {}
```

**Comment by robinp** [comment]
Some comments:

1) I'm not proficient in `Go`, where is the `Bool` coming from? Some default return type? What is the `EmptyTuple` then?

2) What is the motivation for this?

3) Maybe not related, but mentioning in case it is or you have insight:

I contemplated about the `abs`-es of Kythe, and a problem seemed to be that when you define an abstraction binding, the abstract variables are defined in terms of source code anchors. This makes type reuse hard (impossible) between bindings that would otherwise unify, since obviously the absvars have different source location.

See https://github.com/robinp/snippets/blob/master/images/kythe_type_share.jpg, where I sketch a hack to this encoding, where I introduce a `G1` generic `abs`, with its `G1`  `absvar` referring to a builtin, generic var. Then actual binding sites can still abstract over specific anchored vars, and internally `tapp` that to `G1`. This recovers lot of sharing of the types.

What do you think? Is this too hacky? Are there alternatives in trying to recover schema using (or by modifying) the schema?

**Comment by creachadair** [comment]
The Bool was a typo, it's updated now.

**Comment by schroederc** [comment]
1. 

I mistyped that `Bool` at first.  It should have been `EmptyTuple` to represent no return types.  The second `EmptyTuple` is from https://github.com/kythe/kythe/issues/3613.

2.

The motivation is to uniformly represent variadic parameter types between languages and ensure that they are differentiated from language-specific semantics (such as Go variadics being slice types or Java representing them as arrays).

3.

This might be better suited to a kythe@googlegroups discussion.

**Comment by robinp** [comment]
Thank you! My bad, I missed variadic.

Good point, shooting a mail.

**Comment by creachadair** [comment]
> I contemplated about the `abs`-es of Kythe, and a problem seemed to be that when you define an abstraction binding, the abstract variables are defined in terms of source code anchors. This makes type reuse hard (impossible) between bindings that would otherwise unify, since obviously the absvars have different source location.

I think it's important to distinguish between an `absvar` and its binding(s). Of course there often _is_ a binding, but the `absvar` is not itself defined by a location: Just like a "normal" variable it might exist without any explicit binding location, at least in principle. It's possible to have an `absvar` that has no source locations and its ticket should be sufficient to identify its uses elsewhere in the graph. 

Lacking an anchor would of course make it hard to talk about _where_ the variable comes from. You would probably have to do some shenanigan like "scan upward in the type tree until you find somebody who has an anchor".
