### ISSUE TITLE
Support protobuf encoding as well as JSON for kzip

### ISSUE THREAD

**Issue by jaysachs** [kythe/kythe#3633]
When large kzips are ingested, prototypes indicate significant performance gains when using protobuf encoding vs JSON. We propose to support both encodings.

Nominal implementation: compilation unit files in the kzip named <hash>.pb instead of <hash>.

**Comment by creachadair** [comment]
I'm not at all surprised that encoding and decoding are faster with protobuf than JSON. But is this actually causing any real performance issues in production? When reading `.kzip` files from the filesystem, I expect I/O to dominate the cost of unpacking the contents, not decoding—and for cases where the compilations are meant to be processed repeatedly, we typically use a different storage format anyway.

Unless the performance gain affects a real workload rather than a generic read-in benchmark, I wouldn't advocate adding the complexity.

**Comment by shahms** [comment]
It turns out the Go JSONPB library has kind of terrible performance.  I'm not sure if it's just the library or inherent in the use of JSON.  Using proto directly also works around the obstinance in https://github.com/protocolbuffers/protobuf/issues/5226, but is less friendly to indexer authors (as proto is less broadly supported than JSON).

**Comment by shahms** [comment]
Also, the more I think about it, the less I like mixing JSON and proto files in the same container, that's going to be recipe for confusion. If we go that route we should use a different subdirectory to delineate binary protos, rather than just suffix, e.g `$root/units.pb/` or something.  At that point we can mandate that a kzip file has:

1. Both `$root/units` and `$root/units.pb` and that they have identical contents (quick verification is same file counts).
2. Only `$root/units` or `$root/units.pb`.  This will cause decoders that don't understand the binary protos to fail loudly and promptly (the current decoders validate that the kzip file have entries for `$root/` `$root/units` and `$root/files`), rather than only processing a subset of the entries.

**Comment by jaysachs** [comment]
Based on the above and feedback on #3836, I propose a new format. The requirements would be

- The file extension is distinguishable from ".kzip" based on the last segment of a "."-split name. Thus ".pb.kzip" is not an acceptable extension, while ".kpzip" is. I in fact propose the latter.
- The structure of the archive is similar to that of the kzip, except that the directory containing units should be distinct from "units", and also neither should form a prefix of the other. Thus "punits" is an acceptable directory name, while "units.pb" is not.
- The name of the file for each unit is {digest}.pb

**Comment by shahms** [comment]
I don't understand the motivation for the non-prefix requirement in the second bullet point, but the others seem reasonable and fine.

**Comment by jaysachs** [comment]
The second bullet point prefix constraint was to avoid a small fragility in processing kzips; a scan for any files prefixed with "units" (vs "units/") would turn up that the file is not of the expected format. It's very possibly over-cautious, thought.

**Comment by shahms** [comment]
Fair enough, seems fine to me either way (lack of specificity in path prefixes is a pretty common failure mode).
