### ISSUE TITLE
kythe.io "might not be sending the appropriate intermediate certificates"

### ISSUE THREAD

**Issue by KOLANICH** [kythe/kythe#3706]
>kythe.io uses an invalid security certificate. The certificate is not trusted because the issuer certificate is unknown. The server might not be sending the appropriate intermediate certificates. An additional root certificate may need to be imported. Error code: SEC_ERROR_UNKNOWN_ISSUER

**Comment by creachadair** [comment]
I'm having trouble reproducing this message. What browser and OS versions are you using, and is there anything special about how you're connecting?

**Comment by danielmoy-google** [comment]
We did just re-up the cert since it was about to expire, though we used the same method we always do.

I also cannot repro this error though.  Does your browser disallow GTS certs?

**Comment by benjyw** [comment]
We've also encountered this problem, starting with when you re-upped the cert on Thursday. 

From my debugging it appears that the underlying issue is that kythe.io is not sending the entire certificate chain to the client during the handshake. It's only sending its own cert, which is signed by the intermediate CA "GTS CA 1O1", but it's not sending the intermediate CA's cert (which is signed by the well-known root CA GlobalSign).

Most browsers, and curl, can handle this because they'll go search for the intermediate CA's cert. But other clients, such as python's `requests` library, do not support this certificate discovery feature. We're using `requests`, so we hit this issue.

To see this in action, run 

```openssl s_client -prexit  -showcerts  -CAfile ~/Downloads/certs.pem  -connect kythe.io:443  -servername kythe.io```

And compare to, a case that does send the entire certificate chain, e.g., 

```openssl s_client -prexit  -showcerts  -CAfile ~/Downloads/certs.pem  -connect google.com:443  -servername google.com```

We encountered an issue in the past that I now suspect was this same problem (see https://groups.google.com/forum/#!msg/kythe/ZMxGsGvqszo/0FmjjB11AgAJ). But we didn't delve into it then because we had a workaround (requesting insecurely using http). The workaround appears to have stopped working as a result of, or concurrently with, your cert re-up. Not sure why. I notice that the http requests now redirect to https, so maybe that changed along with your cert re-up?

Anyway, presumably the solution is to fix the server config for kythe.io, so that the server send's the entire certificate chain during the handshake (which I'm pretty sure it must do per the TLS spec).

A short-term workaround is to add that intermediate cert to the client's trusted certs bundle. 

PS I'm no expert on any of this, so please excuse any terminology errors.

**Comment by KOLANICH** [comment]
>What browser and OS versions are you using, and is there anything special about how you're connecting?

Firefox. The special thing is that the intermediate certificate is not in the cache. The first post in this issue is the error message given by Firefox.

>From my debugging it appears that the underlying issue is that kythe.io is not sending the entire certificate chain to the client during the handshake.

Yes, it is said right in the error message.

>Most browsers, and curl, can handle this because they'll go search for the intermediate CA's cert.

They search only in cache. If you have recently visited a site sending that intermediate cert (for example material.io), it would work. If you haven't, you will see the error.

>the solution is to fix the server config for kythe.io, so that the server sends the entire certificate chain during the handshake (which I'm pretty sure it must do per the TLS spec).

Definitely, that's why this issue has been created.

**Comment by benjyw** [comment]
> They search only in cache. If you have recently visited a site sending that intermediate cert (for example material.io), it would work. If you haven't, you will see the error.
>

It's not just cache. Most browsers will use Authority Information Access to search for missing intermediate certs. See https://www.thesslstore.com/blog/aia-fetching/:

"Google Chrome on all platforms (except Android), Internet Explorer, and Safari all perform AIA fetching." Which would explain why Firefox is specifically more vulnerable.

**Comment by KOLANICH** [comment]
Thank you for the info.

**Comment by creachadair** [comment]
Even if most browsers do this, it seems like we should try to avoid requiring cert discovery if we can. (However, I can't do anything about it myself, as I no longer have access to any of the site or server configs).

**Comment by benjyw** [comment]
Yep, we would appreciate if this were fixed on the server, since it is technically a violation of the TLS spec not to send the entire cert chain up to (but not including) the root cert. AIA exists because this violation is unfortunately common, but it's truly best not to rely on it, especially on a domain like kythe.io that serves raw Go code and so is more likely to be accessed by non-browser code. 

Thanks!

**Comment by shahms** [comment]
@danielmoy-google recently update the certificate (which was expiring) and may have a better idea on what ha happened

**Comment by benjyw** [comment]
In fact, even the standard Go toolchain breaks on this:

```
gonzo:[~/go]$ go get kythe.io/kythe/go/platform/delimited
package kythe.io/kythe/go/platform/delimited: unrecognized import path "kythe.io/kythe/go/platform/delimited" (https fetch: Get https://kythe.io/kythe/go/platform/delimited?go-get=1: x509: certificate signed by unknown authority)
gonzo:[~/go]$ go get -insecure kythe.io/kythe/go/platform/delimited
gonzo:[~/go]$ 
```

So it definitely seems like the correct fix is on the server, not the clients.

**Comment by benjyw** [comment]
FWIW that `go get` was broken years ago (see https://groups.google.com/forum/#!msg/kythe/ZMxGsGvqszo/0FmjjB11AgAJ) so it's possible that the cert re-up merely exposed the problem rather than causing it.

**Comment by danielmoy-google** [comment]
Yea the process we followed was exactly the same as previous cert updates, so the previous instructions/steps were already flawed.  I'll look into this.

I can confirm repro using benjyw's `openssl` commands above - no TLS session for `kythe.io` using our new cert.

**Comment by danielmoy-google** [comment]
I'm gonna try something else, using google managed certs.  It's mostly to get auto-renewal going though, not to fix this issue.  If it fixes this issue that's great, but I suspect it might... cause other problems.  So if things break I'll go back to old state.

**Comment by danielmoy-google** [comment]
Nope, turns out we're not allowed to use that internally?

**Comment by danielmoy-google** [comment]
Ok this should now be fixed.

Sorry for the flakiness, will update the internal update instructions so it does not happen again.

(I verified that this is fixed simply by opening firefox to kythe.io and no longer getting a SSL warning - if you see it busted in some other scenario still, please re-open and let me know!)

**Comment by benjyw** [comment]
Verified that openssl `s_client -prexit -showcerts -CAfile ~/Downloads/certs.pem -connect kythe.io:443 -servername kythe.io` does the right thing now. Thanks for the quick fix!
