### ISSUE TITLE
Add a VName specification for TypeScript Indexer

### ISSUE THREAD

**Issue by ayazhafiz** [kythe/kythe#3779]
This is a feature proposal for a well-defined VName schema used by the TypeScript indexer.

## Motivation

A project with references across multiple languages can be difficult to index, as generally each language must be indexed individually. It would be nice to have a well-defined VName schema for TypeScript declarations so that other languages that use TypeScript code do not have to re-index a TypeScript project to extract the declarations they need, instead building the VName of the declaration using the formalized specification.

For example, I am developing an Angular indexer, the templating language of which uses TypeScript identifiers declared in other source files.

### Benefits

Makes it easier to write an indexer for a superset/integrator of TypeScript. Reduces duplication of entries generated by indexers.

### Drawbacks

May make future feature development of the the TypeScript indexer more strict. Though I'm not sure this is a drawback.

**Comment by ayazhafiz** [comment]
@evmar

**Comment by shahms** [comment]
Why can you not use `generates` or `imputes` edges like the other languages?  Having a fixed VName format is a potentially huge impediment to future development in that language, so definitely counts as a "drawback".

Another possible approach is that taken by Java/JVM where the lower level has well-defined semantics and a correspondingly well-defined VName schema but the languages built on top of the JVM do not.

**Comment by ayazhafiz** [comment]
`generates` would be a better solution, you're right. Even for this though, it would be nice to have a spec that guarantees the VName of a semantic node. For instance an Angular component has a TypeScript class and HTML template, where the desired behavior is something like

```typescript
class MyComponent {
  someProperty: number;
}
```

```html
<div>{{someProperty}}</div>
```

The desired behavior is something like

```html
@someProperty ref VName("MyComponent.someProperty", _, _, _, _)
<div>{{someProperty}}</div>
```

without the template indexer having to look at the TypeScript source file, making a "best-guess" reference.

**Comment by creachadair** [comment]
Having conventions for the signature is probably fine. It's tricky to constrain the other fields, though, since they usually depend on the build environment. That said: For a source-only language like TS it is probably _less_ problematic, since the usage site has to have the source anyway. The main thing to watch out for in the spec are features the call site can't know without seeing the rest of the build environment (e.g., indirect dependencies).

**Comment by ayazhafiz** [comment]
Right. Since this is intended for supersets of TypeScript, the TypeScript compilation unit will be known, so things like the corpus and root can be inferred from that in the same way that they are passed to the TS indexer. Is there danger in creating a reference to a VName that is not bound to any anchor other than no analysis being generated for it?

**Comment by creachadair** [comment]
> Is there danger in creating a reference to a VName that is not bound to any anchor other than no analysis being generated for it?

No danger—though it does have UI implications. The data model intentionally separates anchors from semantic nodes to allow a distinction to exist between the object and its source code. A UI that finds a semantic node no binding or definition anchors can still display cross-references for it—it just won't be able to show the source definition. This also lets the graph handle multiple source definitions for the same semantic object (type, function, etc.), which is quite common.

So it's generally fine to link to a node whose definition you haven't seen—that's actually the normal state of affairs for languages that support separate compilation (as well as C++). Moreover, it means that if a source definition is discovered later, it can be added without disrupting the existing relationships.

**Comment by ayazhafiz** [comment]
> Moreover, it means that if a source definition is discovered later, it can be added without disrupting the existing relationships.

Gotcha, that's awesome. Definitely the desired behavior and the basis behind this feature.

In terms of the UI implications, it's on the indexer to try to emit as few hanging refs as possible. In a well-compiled Angular program each interpolated variable like `<div>{{prop}}</div>` has to be a member of a class, and the signature conventions will guarantee some node with signature "Class.prop" will be emitted by the TS indexer. I think this is good enough, with the burden of accuracy of course relying on the Angular (or other superset) indexer.

**Comment by creachadair** [comment]
> In terms of the UI implications, it's on the indexer to try to emit as few hanging refs as possible.

This is always a good goal. That said, I will also add that tools should be prepared to deal gracefully with cases where there _are_ references (@—ref—Y) without corresponding (@—defines/binding—Y) edges. Also, they should be prepared for cases where there are multiple definitions, even if there aren't "supposed" to be. Missing either is usually a bug, but each provides some value even without the other.

There are a few cases I've seen over the years:

1. Module A emits @—ref—Y, module B emits @—defines—Y', and Y ≠ Y' but the user expects them to be the same.
2. Module A emits @—ref—Y, and B never gets indexed.
3. Module B emits @—defines—Y, and A never gets indexed.
4. Module A emits @—ref—Y, modules B and C each emit @—defines—Y.

The questions users will ask include:

- "Why doesn't jump-to-definition from line 25 in A go to line 17 in B?" (1), (2)
- "Why don't the xrefs for Y in module B include line 25 in A?" (1), (3)
- "Why do the xrefs for line 25 in A, which imports B, include uses of this definition in C?" (4)
- "Why do the xrefs for line 25 in A, which imports B, only include uses of this definition from C?" (2), (4)

When you're building the index, these are bugs. But debugging them often turns out to reveal other structural issues in the build (non-strict dependencies, unexpected library duplication, version skew, etc.). As long as the UI and other tools that depend on the index can cope with incomplete data, cross-reference bugs can be a valuable source of signal about the presence of these issues, which might otherwise be invisible.
