### ISSUE TITLE
TypeScript indexer: Fix handling of class values and types

### ISSUE THREAD

**Issue by ayazhafiz** [kythe/kythe#3833]
Since cdee8bf8a813ddd0309dbab00110f0e972282996, the structure for class VNames is:

- Class name identifiers refer to the class type and have a node kind of a record
- Class constructors refer to the class value and have a node kind of a function, subkind of constructor. If there is no constructor, the class name takes this.

```typescript
//- @Class defines/binding Class=VName("Class#type", _, _, _, _)
class Class {
  //- @constructor defines/binding ClassCtor=VName("Class:ctor", _, _, _, _)
  constructor() {
    //- @Class ref ClassCtor
    new Class();
  }
}

//- @CC defines/binding VName("CC#type", _, _, _, _)
//- @CC defines/binding VName("CC:ctor", _, _, _, _)
class CC {}
```

This is probably backwards. The constructor should refer to the class type, and the class value should point to the class identifier. This should resolve problems when references to classes are interpreted in a value context and taken to the constructor when they should be taken to the class identifier. The class type and value will both have a node kind of a record.

We should also emit a separate entry for constructors with a signature of `Class.constructor`, for example. This makes scoping parameters and variables inside the constructor much easier, so that while the constructor and class type point to the same thing, they are not actually the same thing. The class constructor will have a node kind of a function with a subkind of a constructor.

**Comment by creachadair** [comment]
Unfortunately, either choice has trade-offs. Broadly, we've found that users expect that the cross-references for an object should include all the things that need to be examined if that object is changed (say, for example, renamed). If the xrefs for the class don't include the constructors, they'll complain. I'd say that complaint has been fairly robust across languages.

On the other hand, when jumping to definition, users often expect the name of a class in a constructor call to go to the constructor and _not_ the class. That means in practice that the UI needs to give the user a choice: This reference might mean the class _or_ the constructor. There might be a reasonable default for J2D, but there's no canonical way to know which one the user really wants (because it depends on what they're doing).

In any case, I suggest caution about forcing the choice between one or the other. This isn't really a decision the indexer can make correctly in isolation. (You can of course do it anyway, my caution is more a prediction of user expectations than a correctness issue).

**Comment by ayazhafiz** [comment]
I think in the case of a class instantiation, the indexer should point to the constructor. In all other cases, it's easiest to simply point to the class name - this harshly defines the class value and class type to be the class name, which is less ambiguous than the class type sometimes being the constructor, sometimes being the class name, etc.

In fact, the only time we call the constructor of a TypeScript class (aside some esoteric use cases) is during instantiation.

**Comment by shahms** [comment]
The indexer should `ref` both, but only `ref/call` the ctor.

**Comment by creachadair** [comment]
> I think in the case of a class instantiation, the indexer should point to the constructor. In all other cases, it's easiest to simply point to the class name

Right—it's pretty clear it should do that either way. But if it doesn't _also_ point to the class, the xrefs for the class will not show them, and I expect users to file bugs about it.
