### ISSUE TITLE
vname ordering question

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#4065]
https://kythe.io/docs/kythe-storage.html#VNameOrder specifies that the lexicographic ordering is Corpus, Language, Path, Root, Signature.

I'm curious about the reason for this ordering. I would have chosen Corpus, Root, Path, Language, Signature because those seem to be from most general to least general ("language" doesn't have an obvious place, although in most cases, it'll be invariant for a given corpus,root,path with the exception of "file" nodes, which seem to be the only ones without a "language").

**Comment by creachadair** [comment]
It's essentially arbitrary, and somewhat historical.

In the original implementation of Grok we partitioned graph storage by language. When I was writing some of the early design docs, we still hadn't completely migrated away from that, so I wanted it to be early in the listing to preserve the grouping. Having language first, however, made certain prefix-scan queries annoying to construct when there were multiple corpora, so I moved `corpus` first. Arguably the only one in the order that really matters is `signature`, which should always be last.

At this point I doubt it really matters—the important thing is that there should be _some_ consistent order so the encoding is canonical. Since we tend to use storage based on sorted keys (e.g., LevelDB, Bigtable) it's convenient to have them cluster naturally by repository and language. I would be surprised if anything relies on that exact permutation, though.

**Comment by kamahen** [comment]
"At this point I doubt it really matters" -- that answers my follow-up question. ;)

It's mildly annoying that the vname ordering in the verifier (signature, corpus, root, path, language) is different, but I suppose that's because (a) most tests shouldn't use vname and (b) signature is usually the most interesting thing to verify.

**Comment by kamahen** [comment]
Am I correct that the only time vname.language is empty is for `file` nodes?

**Comment by creachadair** [comment]
> Am I correct that the only time vname.language is empty is for `file` nodes?

I believe that's the only case where it's explicitly _defined_ as being empty. I'd hesitate to make that a structural rule, though, without reviewing the schema for other implications. In particular, I recommend not writing code that uses `language == ""` as a proxy for `node/kind == "file"`.

For example, we didn't explicitly require anchors to set a `language`, and a `vcs` node probably doesn't need a nonempty `language`. One could make a case for tightening the rules, but I wouldn't rely on it before doing so.

**Comment by kamahen** [comment]
I seem to remember something breaking when `language` wasn't specified for an anchor, but I'm fuzzy on the details (or whether something did break ... I might be confusing this with the obsolete requirement that an anchor be in a `childof` a file).

**Comment by creachadair** [comment]
> I seem to remember something breaking when `language` wasn't specified for an anchor

I _think_ it would be safe to omit a `language` from an anchor—though I believe all our current indexers supply one. The only required implication is that deleting `language` and `signature` from the anchor VName results in the `file` VName (which is how we were able to drop the `childof` edges you mentioned).
