### ISSUE TITLE
Feature request: Split cross references by mutability e.g. reads vs writes

### ISSUE THREAD

**Issue by alancutter** [kythe/kythe#4099]
This is a feature request to have the cross references of a variable split based on whether it was a mutable access or a const access.

Example: https://cs.chromium.org/chromium/src/ui/views/controls/label.h?g=0&l=376&q=full_text_
When looking at the references to the full_text_ member it's not easy to find all the places where it may get mutated. One has to guess based on context.
This would be useful when debugging a variable that's ends up with the "wrong" value and trying to reverse engineer how it could have gotten into that state.

**Comment by jaysachs** [comment]
Something encompassing what you're describing has already been under discussion, and it's quite possible we'll prioritize that effort.

One thing I like about your suggestion is that it's pretty tightly scoped.

**Comment by kamahen** [comment]
It might also be useful to have the notion of "updated". For example, in Python:
```python
a_list = [1,2,3]
a_list.append(4)  # a_list += [4]
a_list2 = a_list + [5]
```

In the first line, `a_list` is in a *binding* context. In the second line, `a_list` is in an *update* context. In the third line, `a_list2` is in a *binding* context and `a_list` is in a *ref* context.

(A common beginner's mistake in Python is misunderstanding mutability vs non-mutability. I suspect that this can lead to subtle bugs, and the Kythe cross-referencing could be used to automate finding such bugs.)

**Comment by robinp** [comment]
I would love this. In Intellij, having the usages separated by read and write are tremendously useful. When debugging, one is usually more interested in write locations, since those are the likely spots of introducing errors.

Note: it is hard to define a universal notion of what is a read/write. @kamahen I see your point, though I would be happy to see a simple binary read/write-or-likely-some-other-funkyness split first, and later refine into update if crucial.

I'm not sure if Kythe is the right tool for static analysis. It's graph is not fine-grained enough for precise edge cases. For now I think static analysis is better done with language-specific tools.
