### ISSUE TITLE
crossreferences for beam-pipelined tables panic with null SourceNode

### ISSUE THREAD

**Issue by robinp** [kythe/kythe#4128]
After using `write_tables` on some random entries, then using the `kythe` tools `xref` command, the server throws a null panic. It seems `cr.SourceNode` below is null (there's a check above in some case to see if it is non-null).

The hack below makes the error go away and references to appear, however I have no idea what am I doing.

```
diff --git a/kythe/go/serving/xrefs/xrefs.go b/kythe/go/serving/xrefs/xrefs.go
index 5b656651..aa8fe18f 100644
--- a/kythe/go/serving/xrefs/xrefs.go
+++ b/kythe/go/serving/xrefs/xrefs.go
@@ -550,9 +550,13 @@ func (t *Table) CrossReferences(ctx context.Context, req *xpb.CrossReferencesReq
                }
 
                // Read the set of indirection edge kinds for the given node kind.
-               nodeKind := nodeKind(cr.SourceNode)
-               indirections := experimentalCrossReferenceIndirectionKinds[nodeKind].
-                       Union(experimentalCrossReferenceIndirectionKinds["*"])
+
+               var indirections stringset.Set
+               if cr.SourceNode != nil {
+                       nodeKind := nodeKind(cr.SourceNode)
+                       indirections = experimentalCrossReferenceIndirectionKinds[nodeKind].
+                               Union(experimentalCrossReferenceIndirectionKinds["*"])
+               }
 
                for _, grp := range cr.Group {
```

/cc @schroederc for related recent changes.

**Comment by isker** [comment]
I have encountered this exact same problem with a JVM extraction I created by following the "End-to-End Java Example" (with my own code) from the README in the distribution.  

@schroederc @shahms, any insights here?  Does this indicate a problem with my data or with kythe itself?

**Comment by kamahen** [comment]
As noted with #4248, the problem seems to go away if the data are accessed using http to a server started with the tables instead of directly reading the tables.

(Something has changed with how tables are generated between v0.0.30 and v0.0.31 (see https://github.com/TreeTide/underhood/issues/12), but I've verified the crash with both v0.0.30 and v0.0.37.

**Comment by shahms** [comment]
I think Cody will have a better idea on this one, but is current on vacation (and I'm oncall so don't have time to take a look at the moment).

**Comment by isker** [comment]
@robinp's patch worked for me, thanks for that.  My problems were persisting even when done through the HTTP server.  The patch to me honestly looks like the correct "real" fix, though I have zero context on any of this.

**Comment by kamahen** [comment]
Does this situation ("data is missing") indicate that the indexer didn't output something that it should have? If so, is there a way of validating the data to find such errors?

**Comment by schroederc** [comment]
The data being missing is another case of the post-processing pipeline not being as thorough as our internal version.

**Comment by kamahen** [comment]
There was missing data from the indexer but the post-processor didn't detect it?
Or: the post-processor didn't process something properly?

In either case, is there a way to figure out what's missing or incorrectly processed?

**Comment by kamahen** [comment]
@schroederc - I didn't understand your response. Are you saying that there's some data missing in the server because the post-processor dropped some of the indexer output and didn't put it to the server tables? 

Also: Is there an easy way to figure out what's missing? E.g., is there a suitable log message that could be added after `cr, err := t.crossReferences(ctx, ticket)`? (If I read the code correctly, it silently keeps going - but I'm guessing that in some circumstances it should complain.)
