### ISSUE TITLE
Minimum clang version?

### ISSUE THREAD

**Issue by kamahen** [kythe/kythe#4160]
The documentation (https://kythe.io/getting-started/#external-dependencies) says that the minimum clang version is 3.8, but it seems that 6.0 is needed (I got an "unknown option" error from linking with 3.8).

But https://github.com/kythe/kythe/commit/d5bc910acea59f171055c333d4ccbf66b7024cf6 seems to imply that the minimum clang version should be 7.x?

It would be nice if dependencies like this had their versions checked, the way the Bazel version is checked.

**Comment by shahms** [comment]
There isn't a reasonable and reliable way of checking compiler versions unless we maintain our own toolchain autoconfig rules, which we do not want to do (again).  They are a gigantic maintenance burden.  The de facto supported versions of the various tools are those used by buildbot.

Please use the kythe mailing list (https://groups.google.com/forum/#!forum/kythe) for questions, rather than the bug tracker.

**Comment by shahms** [comment]
The commit in question has nothing to do with the compiler being used to build kythe, only the expected path for the Clang builtin heads from the LLVM repository.
