### ISSUE TITLE
How to run Kythe for a directory with multiple cpp and java files

### ISSUE THREAD

**Issue by aashish29n** [kythe/kythe#4533]
Hi,

i managed to run Kythe on a single file and generated .kzip file but i need to run cxx_extractor on to a directory.

Steps performed to run cxx_extractor on a single file:-
from opt/kythe/ directory
1) export KYTHE_OUTPUT_DIRECTORY=/data/kythetmp
2) extractors/cxx_extractor   -x c++ -I /opt/kythe/master sample.cpp

it generated a .kzip file in /data/kythetmp
ls  /data/kythetmp
7f558e7fe565c52949f28acad780e5933f75d77cccd86a0eac5005c068d193e9.kzip

But i need to run Kythe directories instead of single file.
Need Help !!!

Thanks,
Aashish Aggarwal

**Comment by shahms** [comment]
Can you send an email to kythe@googlegroups.com ? The issue tracker is better reserved for bugs or feature requests, rather than general inquiries.

As to this issue, it will help us if you can include the build system you're using.  In general, Kythe extractors expect to be integrated into a build system rather than being invoked directly.
