### ISSUE TITLE
How to use generate_compilation_database.sh?

### ISSUE THREAD

**Issue by zypangpang** [kythe/kythe#4999]
Hello, I'm new to bazel and kythe. I just want to generate compile_commands.json for my bazel project. I struggled to use generate_compilation_database.sh for a whole morning with no any luck. So anyone can tell me how to use it correctly or any document? I know it needs kythe code to run, but how should I link kythe repo and my own project?

**Comment by shahms** [comment]
That's not a supported script; it exists solely to be able to run `tools/clang_tidy/clang_tidy.sh` on a fine in the Kythe repository, although that script has itself bit-rotten due to lack of use.

I think your best bet for generating a compile_commands.json from Bazel is going to involve post-processing `bazel aquery`:
```
bazel aquery --output=jsonproto --include_artifacts=false 'mnemonic(CppCompile.*, //...)'
```

The above will spit out a big JSON object whose "actions" key includes the relevant information (although pulling out "file" will require inspecting the command line arguments).
