### ISSUE TITLE
Known good editor setups for working on the C++ indexer?

### ISSUE THREAD

**Issue by varungandhi-src** [kythe/kythe#5413]
I was going through the Contributing docs, and I don't see any mention of how to navigate the C++ indexer code in VS Code or CLion or other editors.

I fiddled around to see if I could get a compilation database for the indexer itself to be emitted, but ran into this issue: https://github.com/grailbio/bazel-compilation-database/issues/101 -- I've been using that extractor successfully in other C++ projects with Bazel, but it doesn't work for Kythe due to the use of `layering_check` in the codebase.

Are there any known editor setups which are known to work?

**Comment by varungandhi-src** [comment]
(I created a GitHub issue because I couldn't access the kythe-dev mailing list which is mentioned in the README. Also, it seems like a nice thing to fix in the docs.

![kythe-dev mailing list error](https://user-images.githubusercontent.com/93103176/198288958-dabdd66e-e363-42b1-a372-e79da13440f3.png))

**Comment by shahms** [comment]
The group exists, I think it just requires you to be signed in to a Google account to access it.

I don't believe any of us use VSCode or CLion so it's hard to provide guidance on how to use them. I personally use nVim with YouCompleteMe and clangd (and a variety of other plugins, but I think those are the main ones).

You can generate a compilation database by running `bazel run //:refresh_compile_commands` (although you may want to run `bazel build //kythe/cxx/...` first so that the generated files can be found by the previous command).

**Comment by varungandhi-src** [comment]
> The group exists, I think it just requires you to be signed in to a Google account to access it.

Yep I thought so too when I was initially signed out, but signing in still gives the same error. 
<img width="1584" alt="image" src="https://user-images.githubusercontent.com/93103176/198414562-d81908b1-9d32-4b83-b67d-29f7a1693263.png">

Maybe it has been made private, where you need to be added separately?

Generating a compilation database should be good enough for VS Code or CLion. Thanks!

**Comment by shahms** [comment]
@schroederc you're an owner of the list, any idea why someone might not be able to join/view it?
