### ISSUE TITLE
java indexer tests fail with --config=java20

### ISSUE THREAD

**Issue by salguarnieri** [kythe/kythe#5743]
`bazel test --config=java20 //kythe/javatests/com/google/devtools/kythe/analyzers/...` fails almost all tests with `Error reading around fact 0`

**Comment by salguarnieri** [comment]
indexer_test fails with:


```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //kythe/javatests/com/google/devtools/kythe/analyzers/java:indexer_test
-----------------------------------------------------------------------------
2023/07/18 21:40:53 error decoding Entry: proto: cannot parse invalid wire-format data
Jul 18, 2023 9:40:55 PM com.google.devtools.kythe.analyzers.java.KytheJavacAnalyzer analyzeCompilationUnit
WARNING: Analyzer received compilation unit vname with empty corpus: signature: "#5e0ca3936334b0a95b9c6f3d71428329a5c4d26f3b7a87712652915b43049a12"
language: "java"
```

**Comment by shahms** [comment]
Yeah, this is because HotSpot logs to stdout when it can't open `/tmp/hsperf_{username}/{pid}`, which corrupts the indexer's output.  It's genuinely terrible behavior, which is pretty par for the course.  See https://github.com/bazelbuild/bazel/issues/3236

This should've been fixed by adding `common --incompatible_sandbox_hermetic_tmp` to `.bazelrc`
